INSERT INTO ESTUDIANTE (NOMBRE, APELLIDO, EMAIL, CREDITOS, SEMESTRE, PROMEDIO) VALUES('Angel', 'Guerra', 'aguerralozano@gmail.com', 20, 1, 11);

INSERT INTO ESTUDIANTE (NOMBRE, APELLIDO, EMAIL, CREDITOS, SEMESTRE, PROMEDIO) VALUES('Juan', 'Perez', 'juanperez@gmail.com', 19, 2, 15);
