INSERT INTO TEST_GH.ESTUDIANTE (ID, NOMBRE, APELLIDO, EMAIL, CREDITOS, SEMESTRE, PROMEDIO) VALUES(TEST_GH.ESTUDIANTE_SEQ.nextval, 'Angel', 'Guerra', 'aguerralozano@gmail.com', 20, 1, 11);

INSERT INTO TEST_GH.ESTUDIANTE (ID, NOMBRE, APELLIDO, EMAIL, CREDITOS, SEMESTRE, PROMEDIO) VALUES(TEST_GH.ESTUDIANTE_SEQ.nextval, 'Juan', 'Perez', 'juanperez@gmail.com', 19, 2, 15);
